adm_program/installation/db_scripts/db.sql
adm_program/modules/inventory/fields_new.php
adm_program/modules/inventory/inventory.php
adm_program/modules/inventory/item.php
adm_program/modules/inventory/item_new.php
adm_program/modules/preferences/preferences.php
adm_program/modules/preferences/preferences_function.php
adm_program/modules/roles/roles.php
adm_program/modules/roles/roles_function.php
adm_program/modules/roles/roles_new.php
adm_program/system/classes/htmlform.php
adm_program/system/classes/inventory.php
adm_program/system/classes/organization.php
adm_program/system/classes/user.php
adm_themes/modern/my_body_bottom.php

add some updates for inventory modul
add settings for inventory modul
add role settings for inventory
add FIELD_READONLY on "addInput" -> "property" so we can block entry and
send value by post (block role settings update in last version)

update for inventory and a bugfix

---

adm_program/installation/db_scripts/preferences.php
adm_program/installation/db_scripts/update_3_0.xml
adm_program/languages/de.xml

little changes to get a clean update from versions 2.4

change for clean update

---

adm_program/modules/inventory/item.php
adm_program/modules/inventory/item_new.php
adm_program/modules/inventory/item_photo_edit.php
adm_program/modules/inventory/item_photo_show.php
adm_program/modules/inventory/item_save.php
adm_program/modules/messages/messages_send.php

some updates on inventory and fix for #16

Inventory and #16

---

adm_program/languages/de.xml
adm_program/modules/messages/messages.php
adm_program/modules/messages/messages_send.php
adm_program/modules/messages/messages_write.php
adm_program/modules/messages/process.php
adm_program/system/classes/email.php

possibility to delete Email and mark PM for delete (need confirm from
other person)

solution for #11

---

adm_program/system/classes/email.php

Fix Spelling Error

---

adm_program/installation/db_scripts/preferences.php
adm_program/installation/installation.php
adm_program/installation/update.php
adm_program/system/classes/passwordhashing.php
adm_program/system/classes/tableusers.php

please check if my logic is correct! didn't tested it ;-)

set hashcost preference by benchmark

---

adm_program/languages/da.xml
adm_program/languages/de.xml
adm_program/languages/de_sie.xml
adm_program/languages/en.xml
adm_program/languages/fr.xml
adm_program/languages/it.xml
adm_program/languages/nl.xml
adm_program/modules/categories/categories.php
adm_program/modules/categories/categories_new.php
adm_program/modules/lists/lists_show.php

add module name to category headline

---

adm_plugins/random_photo/random_photo.php
adm_program/installation/db_scripts/db.sql
adm_program/installation/db_scripts/update_3_1.xml
adm_program/modules/announcements/announcements.php
adm_program/modules/announcements/announcements_function.php
adm_program/modules/ecards/ecards.php
adm_program/modules/photos/photo_album_function.php
adm_program/modules/photos/photo_album_new.php
adm_program/modules/photos/photo_download.php
adm_program/modules/photos/photos.php
adm_program/modules/photos/rss_photos.php
adm_program/system/classes/componentupdate.php
adm_program/system/classes/moduleannouncements.php
adm_program/system/classes/organization.php
adm_program/system/classes/tableannouncement.php
adm_program/system/classes/tablephotos.php
adm_program/system/file_upload.php

#130
@ximex can you review and merge this

Feature remove org shortname constraint

---

adm_program/installation/installation.php
adm_program/installation/update.php
adm_program/languages/da.xml
adm_program/languages/de.xml
adm_program/languages/de_sie.xml
adm_program/languages/en.xml
adm_program/languages/it.xml

Feature install with config

---

adm_program/languages/de.xml
adm_program/modules/lists/lists.php
adm_program/modules/lists/lists_show.php
adm_program/system/classes/listconfiguration.php

Feature 203 date range filter in lists

---

adm_program/installation/db_scripts/preferences.php
adm_program/languages/de.xml
adm_program/modules/photos/photo_show.php
adm_program/modules/preferences/preferences.php

- added to photo module preferences
- added to preferences of db_scripts
Please have a look of the decription phrase. hope everybody feel
confident with it?

Implemented caption size in preferences

---

adm_program/modules/dates/dates.php
adm_program/modules/lists/lists_show.php
adm_program/system/classes/htmlelement.php
adm_program/system/classes/htmlform.php

new field type FIELD_HIDDEN

---

adm_program/languages/de.xml
adm_program/modules/lists/members_assignment.php
adm_program/modules/members/members.php
adm_program/modules/roles/roles.php
adm_program/system/classes/htmltable.php

add order data attributes to table

---

adm_program/languages/de.xml
adm_program/system/lost_password.php

#31 LostPassword now works also with username

---

adm_my_files/config_example.php
adm_program/system/classes/passwordhashing.php
adm_program/system/classes/user.php
adm_program/system/common.php

add SHA512 method for password hashing

---

adm_program/modules/userrelations/userrelations_new.php
adm_program/system/classes/htmlform.php

Use select2 when creating new relationships

---

adm_program/installation/db_scripts/db.sql
adm_program/installation/db_scripts/update_3_2.xml
adm_program/languages/de.xml
adm_program/modules/announcements/announcements.php
adm_program/modules/announcements/announcements_function.php
adm_program/modules/announcements/announcements_new.php
adm_program/modules/categories/categories.php
adm_program/modules/categories/categories_function.php
adm_program/modules/categories/categories_new.php
adm_program/modules/links/rss_links.php
adm_program/modules/preferences/preferences.php
adm_program/system/classes/componentupdate.php
adm_program/system/classes/moduleannouncements.php
adm_program/system/classes/organization.php
adm_program/system/classes/tableaccess.php
adm_program/system/classes/tableannouncement.php
adm_themes/modern/css/admidio.css

Feature announcements enhancements

---

adm_program/installation/update.php
adm_program/languages/de.xml
adm_program/modules/announcements/announcements_function.php
adm_program/modules/categories/categories_function.php
adm_program/modules/dates/dates_function.php
adm_program/modules/guestbook/guestbook_function.php
adm_program/modules/inventory/item_photo_edit.php
adm_program/modules/links/links_function.php
adm_program/modules/links/links_redirect.php
adm_program/modules/lists/mylist_function.php
adm_program/modules/members/import_function.php
adm_program/modules/members/members_function.php
adm_program/modules/photos/photo_album_function.php
adm_program/modules/profile/profile_photo_edit.php
adm_program/modules/profile/profile_save.php
adm_program/modules/registration/registration.php
adm_program/modules/registration/registration_assign.php
adm_program/modules/registration/registration_function.php
adm_program/modules/rooms/rooms_function.php
adm_program/modules/userrelations/relationtypes_function.php
adm_program/modules/userrelations/userrelations_function.php
adm_program/system/back.php
adm_program/system/function.php
adm_program/system/login_valid.php
adm_program/system/logout.php
adm_program/system/redirect.php
index.php

Improve and secure redirecting. It is one of the OWASP Top 10.
See: https://www.owasp.org/index.php/Open_redirect

Improve redirecting

---

adm_program/languages/de.xml
adm_program/modules/lists/lists_show.php
adm_program/modules/messages/messages_functions.php
adm_program/modules/messages/messages_send.php
adm_program/modules/messages/messages_write.php

Write mail to lists

---

adm_program/modules/lists/lists_show.php

https://www.admidio.org/forum/viewtopic.php?f=11&t=7267

If-query improved

---

adm_program/installation/db_scripts/update_3_3.xml
adm_program/installation/installation.php
adm_program/languages/de.xml
adm_program/modules/dates/dates.php
adm_program/modules/lists/members_assignment_data.php
adm_program/modules/members/members_assign.php
adm_program/modules/profile/profile.php
adm_program/modules/registration/registration_assign.php
adm_program/system/classes/organization.php
adm_program/system/classes/user.php
adm_program/system/msg_window.php

Rename user field "Address" to "Street" #489

---

adm_program/languages/de.xml
adm_program/modules/inventory/item.php
adm_program/modules/profile/profile.js
adm_program/modules/profile/profile.php
adm_themes/modern/css/admidio.css

Feature profile bootstrap improvement

---

adm_program/languages/de.xml
adm_program/modules/lists/lists.php
adm_program/modules/lists/lists_show.php
adm_program/modules/lists/mylist.php
adm_program/modules/lists/mylist_function.php
adm_program/system/classes/listconfiguration.php
adm_program/system/classes/user.php

Feature: show former members for role leaders

---

adm_program/installation/db_scripts/db.sql
adm_program/installation/db_scripts/update_3_3.xml
adm_program/languages/de.xml
adm_program/modules/preferences/preferences.php
adm_program/modules/userrelations/relationtypes.php
adm_program/modules/userrelations/relationtypes_function.php
adm_program/modules/userrelations/relationtypes_new.php
adm_program/system/classes/user.php

Feature edit profile of relationships

---

adm_program/installation/installation.php
adm_program/installation/update.php
adm_program/system/autoload.php
adm_program/system/bootstrap.php
adm_program/system/common.php
adm_program/system/function.php
adm_program/system/init_globals.php
demo_data/build.php

- Separate autolading from admidio functions
- Separate non DB bootstrapping things
- Simplify bootstrapping in different files with new bootstrap file

Improve bootstrapping

---

adm_program/installation/install_steps/welcome.php
adm_program/modules/backup/backup.functions.php
adm_program/modules/inventory/item_photo_edit.php
adm_program/modules/members/import.php
adm_program/modules/messages/messages_write.php
adm_program/modules/preferences/preferences.php
adm_program/modules/profile/profile_photo_edit.php
adm_program/system/ckeditor_upload_handler.php
adm_program/system/classes/email.php
adm_program/system/classes/image.php
adm_program/system/classes/phpini.php
adm_program/system/file_upload.php
adm_program/system/function.php
adm_program/system/msg_window.php

PhpIni Class

---

adm_program/modules/ecards/ecards.php
adm_program/modules/photos/photo_presenter.php
adm_program/modules/photos/photo_show.php
adm_program/modules/photos/photos.php
adm_program/system/classes/database.php
adm_program/system/classes/profilefields.php
adm_program/system/classes/session.php
adm_program/system/classes/tableaccess.php
adm_program/system/classes/user.php
adm_program/system/common.php
adm_program/system/file_upload.php

Feature make database serializeable

---

adm_program/modules/photos/photo_album_function.php
adm_program/modules/photos/photo_album_new.php
adm_program/modules/photos/photo_download.php
adm_program/modules/photos/photo_function.php
adm_program/modules/photos/photo_presenter.php
adm_program/modules/photos/photo_show.php
adm_program/modules/photos/photos.php
adm_program/modules/photos/rss_photos.php
adm_program/system/classes/tablephotos.php

- use methods for checks of visible and editable of photo albums
- move lock and unlock mode to photo_album_function

Feature photos simplify checks

---

adm_program/languages/de.xml
adm_program/languages/en.xml
adm_program/modules/preferences/preferences.php
adm_program/system/function.php

Adds a progress-bar of the used disk space

Feature disk space

---

adm_plugins/birthday/birthday.php
adm_plugins/calendar/calendar.php
adm_plugins/login_form/login_form.php
adm_plugins/sidebar_announcements/sidebar_announcements.php
adm_plugins/sidebar_dates/sidebar_dates.php
adm_plugins/sidebar_downloads/sidebar_downloads.php
adm_plugins/sidebar_online/sidebar_online.php
adm_program/system/classes/language.php
adm_program/system/classes/languagedata.php
demo_data/build.php

Refactor language

---

adm_program/modules/preferences/preferences.php
adm_program/system/classes/filesystemutils.php
adm_program/system/function.php

A class that handles nearly all file system stuff and has nearly all checks (is writable, ...)
This class should replace `MyFiles` and `Folder` classes.

add new FileSystemUtils class

---

adm_program/system/classes/email.php

fixed duplicate line breaks in email messages

---

adm_program/installation/db_scripts/upd_2_2_0_conv.php
adm_program/installation/db_scripts/upd_2_4_0_conv.php
adm_program/installation/install_functions.php
adm_program/installation/install_steps/start_installation.php
adm_program/installation/installation.php
adm_program/installation/update_functions.php
adm_program/modules/backup/backup_script.php
adm_program/system/classes/componentupdate.php
adm_program/system/classes/componentupdatesteps.php
adm_program/system/classes/tablecategory.php
adm_program/system/constants.php
demo_data/build.php

So we need no global import any more and the table prefix should be a constant

add and use new TABLE_PREFIX const

---

adm_plugins/calendar/calendar.php
adm_plugins/calendar/config.php

- fixed order of names
- fixed sql sorting
- implemented config for type of names to be displayed

- fix for issue #325

---

adm_program/languages/da.xml
adm_program/languages/de.xml
adm_program/languages/de_sie.xml
adm_program/languages/en.xml
adm_program/languages/fr.xml
adm_program/languages/it.xml
adm_program/languages/nb.xml
adm_program/languages/nl.xml
adm_program/languages/pt.xml
adm_program/modules/preferences/preferences.php
adm_program/system/classes/SystemInfoUtils.php
adm_themes/modern/css/admidio.css

Regroup some settings and add more system information

Improve preferences

---

adm_plugins/birthday/birthday.php
adm_plugins/birthday/config_sample.php

Ich habe mir das Template für die Übersicht inzwischen angepasst, dank Bootstrap kann man ja auch viel über CSS realisieren. Allerdings stört mich oftmals die stark unterschiedliche Größe der Plugins. Bei den meisten Plugins kann die Anzahl der maximalen Einträge ja definiert werden (Termine, Dateien, Ankündigungen) oder aber direkt die Größe vorgegeben werden (random photo). Bei der Liste der Geburtstage ist das bisher nicht möglich.

Birthday List with Limit

---

adm_program/system/classes/FileSystemUtils.php

Replace mb_ereg_replace with preg_replace in adm_program/system/classes/FileSystemUtils.php for php7.4 compatibility.

Replace mb_ereg_replace with preg_replace for php7.4 compatibility

---

adm_program/languages/de.xml
adm_program/languages/en.xml
adm_program/modules/messages/messages_send.php
adm_program/modules/preferences/preferences.php
adm_program/modules/preferences/preferences_function.php
adm_program/system/classes/Email.php

  Send Testmail #843

---

adm_program/installation/db_scripts/preferences.php
adm_program/installation/db_scripts/update_4_1.xml
adm_program/languages/de.xml
adm_program/languages/en.xml
adm_program/modules/members/members_data.php
adm_program/modules/members/members_function.php
adm_program/modules/preferences/preferences.php
adm_program/modules/preferences/preferences_function.php
adm_program/modules/profile/profile.js
adm_program/modules/registration/registration_function.php
adm_program/system/classes/Email.php
adm_program/system/classes/SystemMail.php
adm_program/system/classes/UserRegistration.php
adm_program/system/lost_password.php

Change takeover user data registration

---

.gitattributes
Dockerfile
README-Docker.md
README.md
dockerscripts/healthcheck.sh
dockerscripts/startup.sh
hooks/build

* Add docker usage help to README.md
* create README-Docker.md with detailed docker usage help
Dockerfile improvments:
* Add healthcheck
* Install postfix to support mail delivery
* Install trivy to scan for security issues during image build
* Add build lables
* Add many configuration variables
* Add custom dockerhub build hook

Dockerfile improvements

---

adm_program/installation/db_scripts/preferences.php
adm_program/installation/db_scripts/update_4_1.xml
adm_program/languages/de.xml
adm_program/languages/en.xml
adm_program/modules/groups-roles/lists_show.php
adm_program/modules/members/members.php
adm_program/modules/members/members_data.php
adm_program/modules/preferences/preferences.php
adm_program/system/classes/ComponentUpdateSteps.php
adm_program/system/classes/HtmlTable.php
adm_program/system/classes/ListConfiguration.php
adm_program/system/classes/Organization.php
adm_program/system/classes/ProfileFields.php
adm_program/system/classes/TableLists.php

Feature customize user management

---

README-Docker.md

see: https://www.admidio.org/forum/viewtopic.php?f=20&t=8871&p=31549&hilit=traefik#p31549
Fixes point 2 and subsequent errors 1 and 3.

Fix volume path for ubi8 base image in README-Docker.md

---

adm_program/modules/backup/backup_script.php

Views in the database with admidio's table prefix broke the database backup.
This patch special-cases views and handles database tables and database views
separately. This fixes the crash when a view exists, and backs up the view definition.
Fixes #1091.

Fix #1091: Handle Views in the DB backup separately (and back up the definition)

---

adm_program/modules/backup/backup_script.php

Since views can depend on each other in any order, the DB backup needs to create surrogate tables for each view, which provide the columns of the view, first. After all these surrogate tables are created and all columns are available, they are replaced one-by-one by the actual view definitions.
This approach is also taken e.g. by phpmyadmin's export function.

DB backup: For database views, we need to create intermediate tables

---

Dockerfile
LICENSE

- add org.label-schema.license=GPL-2.0 to Dockerfile
, rename LICENSE.txt to LICENSE

Dockerfile: add org.label-schema.license to GPL-2.0

---

adm_program/libs/server/composer/ClassLoader.php
adm_program/libs/server/composer/autoload_classmap.php
adm_program/libs/server/composer/autoload_static.php
adm_program/modules/messages/messages_write.php
adm_program/system/classes/TableMessage.php
adm_program/system/classes/TableMessageContent.php

If you have text mails activated and send a message with line breaks, Admidio will not show these line breaks if you view the message.
view forum https://www.admidio.org/forum/viewtopic.php?f=3&t=8947

Line breaks in plain text messages aren't shown

---

adm_program/languages/de.xml
adm_program/languages/en.xml
adm_program/libs/server/composer/autoload_classmap.php
adm_program/libs/server/composer/autoload_static.php
adm_program/modules/categories/categories_new.php
adm_program/modules/members/members.php
adm_program/modules/menu/menu_new.php
adm_program/modules/photos/photo_album_new.php
adm_program/modules/preferences/preferences.php
adm_program/modules/profile/profile.php
adm_program/modules/userrelations/userrelations_new.php
adm_program/system/classes/HtmlNavbar.php
adm_program/system/classes/HtmlPage.php
adm_program/system/classes/MainMenu.php
adm_program/system/classes/MenuDatabase.php
adm_program/system/classes/MenuNode.php
adm_program/system/common.php
adm_themes/simple/css/admidio.css
adm_themes/simple/templates/index.tpl

Improve page menu

---

adm_program/installation/db_scripts/preferences.php
adm_program/installation/db_scripts/update_4_2.xml
adm_program/installation/install_steps/create_organization.php
adm_program/languages/de.xml
adm_program/languages/en.xml
adm_program/modules/announcements/announcements_function.php
adm_program/modules/dates/dates_function.php
adm_program/modules/guestbook/guestbook_function.php
adm_program/modules/links/links_function.php
adm_program/modules/photos/photo_album_function.php
adm_program/modules/preferences/preferences.php
adm_program/modules/preferences/preferences_function.php
adm_program/system/classes/ChangeNotification.php
adm_program/system/classes/Email.php
adm_program/system/classes/Organization.php
adm_program/system/classes/UploadHandlerDownload.php

Feature send notification to role

---

adm_program/languages/bg.xml
adm_program/languages/da.xml
adm_program/languages/de-DE.xml
adm_program/languages/de.xml
adm_program/languages/el.xml
adm_program/languages/en.xml
adm_program/languages/es.xml
adm_program/languages/fi.xml
adm_program/languages/fr.xml
adm_program/languages/id.xml
adm_program/languages/it.xml
adm_program/languages/nb.xml
adm_program/languages/nl.xml
adm_program/languages/pt-BR.xml
adm_program/languages/pt.xml
adm_program/languages/sv.xml
adm_program/languages/sw.xml
adm_program/languages/zh.xml
adm_program/modules/backup/backup.php
adm_program/modules/groups-roles/mylist.php
adm_program/system/bootstrap/function.php
adm_program/system/classes/Language.php
adm_program/system/classes/ListConfiguration.php

Add createdat lastchanged to own list

---

adm_program/modules/documents-files/documents_files_function.php
adm_program/system/classes/TableFolder.php

Feature add folder recursively

---

adm_program/installation/db_scripts/db.sql
adm_program/installation/db_scripts/update_4_2.xml
adm_program/installation/update_functions.php
adm_program/system/classes/Component.php
adm_program/system/classes/ComponentUpdate.php
adm_program/system/classes/Database.php
adm_program/system/classes/TableAccess.php
composer.json

Improve version update

---

adm_program/system/classes/HtmlPage.php
adm_program/system/classes/MainMenu.php
adm_themes/simple/templates/index.tpl

By this changes you are able to generate your own style of menu in a smarty template.

Changed the menu access and added the possibility to easily change it in custom templates

---

adm_program/modules/rooms/rooms.php

Hello,
I hope that fix is in the right way. I don't code that often, but this one looked quite simple.
We use this fix now for our side, because it looks like everything is working now.
Thanks and have a nice day.

Fixes my Issue (#1300)

---

dockerscripts/startup.sh

Docker support for change #1345

Organization should be optional set within config.php in Docker

---

Dockerfile
dockerscripts/startup.sh

Dockerfile: update php to version 8.2.3-apache-bullseye

---

adm_program/system/classes/HtmlPage.php
adm_program/system/classes/MainMenu.php
adm_program/system/classes/MenuNode.php
adm_program/system/common.php
adm_themes/simple/templates/index.tpl

Until now we had generate html code and implement that html code into an object and call the rendering method within the smarty template.
Now we generate array with the menu strukture and implement the html in the Smarty template.

Implement navigation and functions menu within Smarty template

---

README.md

fixed several typos, punctuations, and grammatical mistakes in README.md for better readability

fix: typos, punctuation, and grammatical mistakes in README.md

---

.github/workflows/build_branches.yml

Only run github workflows on admidio/admidio repo, not on forks

---

Dockerfile
dockerscripts/startup.sh
hooks/build

Merge Docker improvements to master

---

Dockerfile
dockerscripts/healthcheck.sh

- use /index.php for check
- install curl in ubuntu base image

Fix dockerscripts/healthcheck.sh

---

README.md
adm_program/modules/groups-roles/groups_roles_function.php
adm_program/modules/profile/profile_function.php
adm_program/system/classes/User.php

Migrate from vCard 2.1 to vCard 3.0 with utf-8

---

adm_program/system/classes/ListConfiguration.php
adm_program/system/classes/ListData.php

Improvement of the export via PhpSpreadsheet for line breaks in cells for Windows / MacOS / Linux

improve line break compatibility for PhpSpreadsheet

---

adm_program/modules/contacts/contacts_data.php
adm_program/system/classes/ListConfiguration.php

Case-Insensitive search in contacts data independent of db collation

Case-Insensitive searches using Lower()

---

.dockerignore
Dockerfile

Dockerfile: Update from ubuntu 22.04 to ubuntu 24.04

---

adm_program/languages/de-DE.xml
adm_program/languages/de.xml
install/db_scripts/update_4_3.xml
install/install_steps/start_installation.php
install/installation.php
src/Events/Entity/Event.php
src/Infrastructure/ChangeNotification.php
src/Infrastructure/Entity/Entity.php
src/ProfileFields/ValueObjects/ProfileFields.php
src/UI/View/GroupsRoles.php
src/Users/Entity/User.php
src/Users/Entity/UserRelationType.php

Forward port of the patches from v4.3 to master.

Master: forward-port small fixes

---

adm_plugins/announcement-list/announcement-list.php
adm_plugins/birthday/birthday.php
adm_plugins/calendar/calendar.php
adm_plugins/calendar/templates/plugin.calendar.tpl
adm_plugins/event-list/event-list.php
adm_plugins/latest-documents-files/latest-documents-files.php
adm_plugins/login_form/login_form.php
adm_plugins/random_photo/random_photo.php
adm_plugins/who-is-online/who-is-online.php
adm_program/system/classes/HtmlPage.php
src/Infrastructure/Plugins/Overview.php
src/Infrastructure/Plugins/Smarty.php
src/UI/Presenter/PagePresenter.php
themes/simple/css/admidio.css
themes/simple/templates/index.reduced.tpl

Overview plugins html

---

adm_program/modules/contacts/contacts_data.php
src/UI/Presenter/FormPresenter.php
themes/simple/templates/sys-template-parts/form.custom-content.tpl
themes/simple/templates/system/login.tpl

Lots of tiny fixes / improvements for form / UI generation

Tiny fixes for master (mainly in Presenters / UI elements)

---

src/UI/Presenter/CategoriesPresenter.php

Fix the label for the edit right input field on the category edit screen

---

Dockerfile
README-Docker.md
dockerscripts/startup.sh
hooks/build

- [*] install cron daemon
- [*] start cron service on container startup
- [*] update docker compose example

Install and run cron service in docker container for php session files cleanup (#1767)

---

Dockerfile
README-Docker.md
dockerscripts/startup.sh
hooks/build

[*] install cron daemon
[*] start cron service on container startup
[*] update docker compose example

Install and run cron service in docker container for php session files cleanup

---

languages/de.xml
languages/en.xml
modules/groups-roles/mylist.php
modules/profile/roles_functions.php
src/Roles/Entity/ListConfiguration.php
src/Roles/Entity/Membership.php
system/classes/CategoryReport.php
themes/simple/templates/modules/profile.roles-list.row.tpl

feat: Add showing duration of role in profile

---

install/db_scripts/db.sql
install/db_scripts/update_5_0.xml
languages/de-DE.xml
languages/de.xml
languages/en.xml
modules/links/links.php
modules/links/links_function.php
src/Changelog/Service/ChangelogService.php
src/InstallationUpdate/Service/UpdateStepsCode.php
src/Weblinks/Entity/Weblink.php
system/classes/ModuleWeblinks.php

add sequence to weblinks to manage the order of web links within categories
Closes: #900

Feat weblinks sequence

---

modules/category-report/category_report.php

fixes: #1842 
After merging the changes also has to be applied to the 4.3 branch.

Feat category report xlsx

---

modules/groups-roles/lists_show.php

- hide filter options (Members, Startdate, Enddate)
- show only active members if the event is upcoming
- show all members if the event has alreay occured

Changes event participation list
